# Generated by Django 5.0.1 on 2024-01-29 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Device_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "employee_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("employee_name_full", models.CharField(max_length=400)),
                ("grade", models.CharField(blank=True, max_length=25, null=True)),
                ("position", models.CharField(blank=True, max_length=400, null=True)),
                ("employee_department", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("device_serial", models.CharField(max_length=30)),
                ("receipt_number", models.CharField(max_length=30)),
                ("cleared", models.CharField(default="0", max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("device_status", models.CharField(max_length=30)),
                ("issue_date", models.DateTimeField()),
                ("update_date", models.DateTimeField()),
                (
                    "brand_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mcd.brand"
                    ),
                ),
                (
                    "device_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mcd.device_type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee_Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_number", models.CharField(max_length=30)),
                ("receipt_number", models.CharField(max_length=30)),
                ("receiving_status", models.CharField(max_length=30)),
                ("return_status", models.CharField(max_length=30)),
                ("issue_date", models.DateTimeField()),
                ("update_date", models.DateTimeField()),
                (
                    "device_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mcd.device"
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mcd.employees"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mcd_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("sim_serial_number", models.CharField(max_length=50)),
                ("service_number", models.CharField(max_length=12)),
                ("short_code", models.CharField(max_length=10)),
                ("cleared", models.CharField(max_length=10)),
                ("display_name", models.CharField(max_length=100)),
                ("current_id", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=10)),
                ("package", models.CharField(max_length=10)),
                ("payment_value", models.CharField(max_length=30)),
                ("PUK", models.CharField(max_length=30)),
                ("PIN", models.CharField(max_length=30)),
                ("request_number", models.CharField(max_length=20)),
                ("comments", models.CharField(max_length=100)),
                ("issue_date", models.DateTimeField()),
                ("update_date", models.DateTimeField()),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mcd.employees"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mcd_Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("sim_serial_number", models.CharField(max_length=50)),
                ("mobile_number", models.CharField(max_length=9)),
                ("short_code", models.CharField(max_length=10)),
                ("cleared", models.CharField(max_length=10)),
                ("display_name", models.CharField(max_length=100)),
                ("current_id", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=10)),
                ("package", models.CharField(max_length=10)),
                ("payment_value", models.CharField(max_length=30)),
                ("PUK", models.CharField(max_length=30)),
                ("PIN", models.CharField(max_length=30)),
                ("request_number", models.CharField(max_length=20)),
                ("comments", models.CharField(max_length=100)),
                ("issue_date", models.DateTimeField()),
                ("update_date", models.DateTimeField()),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mcd.employees"
                    ),
                ),
            ],
        ),
    ]
